apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitor-deploy-production

resources:
  - ../../base
  - namespace.yaml

images:
  - name: registry.example.com/monitor-deploy/api
    newTag: "0000000000000000000000000000000000000001"
  - name: registry.example.com/monitor-deploy/vue-app
    newTag: "0000000000000000000000000000000000000001"

patches:
  - path: env-patch.configmap.yaml
    target:
      kind: ConfigMap
      name: env-config
  - path: api-deployment-patch.yaml
    target:
      kind: Deployment
      name: api
  - path: vue-deployment-patch.yaml
    target:
      kind: Deployment
      name: vue-app
